title: blank
first_name: Dustin
last_name: Steiner
email: dustin@meecolabs.eu
description: >-
  Dustin Steinerâ€™s personal website

icon: ğŸ‘¨â€ğŸ’»
url: "dustin.meecolabs.eu"
baseurl: ""
last_updated: false

navbar_fixed: true
footer_fixed: true

max_width: 800px

serve_og_meta: true

twitter_username: alopix
github_username: alopix

# Build settings
# theme: minima
remote_theme: alshedivat/al-folio
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - bin
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
keep_files:
  - CNAME
  - .git
  - .gitkeep

enable_darkmode: true
