title: Dustin Steiner
icon: ðŸ‘¨â€ðŸ’»
description: >-
  Dustin Steinerâ€™s personal website.

url: 'dustin.meecolabs.eu'
baseurl: ''

first_name: Dustin
last_name: Steiner
job_title: Software Engineer
email: dustin@meecolabs.eu

social:
  - name: Twitter
    icon: fab fa-twitter-square
    url: https://twitter.com/alopix
  - name: GitHub
    icon: fab fa-github-square
    url: https://github.com/alopix
  - name: LinkedIn
    icon: fab fa-linkedin
    url: https://www.linkedin.com/in/dustin-steiner
  - name: Goodreads
    icon: fab fa-goodreads
    url: https://www.goodreads.com/author/show/18550140.Dustin_Steiner
  - name: E-Mail
    icon: fas fa-envelope-square
    url: 'mailto:dustin@meecolabs.eu'

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-avatar
