title: Dustin Steiner
icon: ðŸ‘¨â€ðŸ’»
description: >-
  Dustin Steinerâ€™s personal website.

url: "dustin.meecolabs.eu"
baseurl: ""

first_name: Dustin
last_name: Steiner
job_title: Software Engineer
email: dustin@meecolabs.eu

social:
  - name: E-Mail
    icon: fas fa-envelope
    url: "mailto:dustin@meecolabs.eu"
  - name: Twitter
    icon: fab fa-twitter
    url: https://twitter.com/alopix
  - name: GitHub
    icon: fab fa-github
    url: https://github.com/alopix
  - name: LinkedIn
    icon: fab fa-linkedin-in
    url: https://www.linkedin.com/in/dustin-steiner

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-avatar
